ALTER SESSION SET CONTAINER=RSA;

COMMENT ON TABLE REGIONE_ITALIANA IS 'Regioni italiane (ISTAT)';
COMMENT ON TABLE PROVINCIA_ITALIANA IS 'Province italiane con sigla';
COMMENT ON TABLE CITTA_ITALIANA IS 'Comuni italiani con codice ISTAT';
COMMENT ON TABLE TIPO_CONTRATTO_DEF IS 'Tipologie contrattuali';
COMMENT ON TABLE TURNO_DEF IS 'Tipologie di turno lavorativo';
COMMENT ON TABLE SPECIALIZZAZIONE IS 'Specializzazioni mediche';
COMMENT ON TABLE QUALIFICA_DEF IS 'Qualifiche del personale (OSS, infermiere)';
COMMENT ON TABLE STATO_SALUTE_DEF IS 'Stati di salute dei residenti';
COMMENT ON TABLE FASCIA_ORARIA_DEF IS 'Fasce orarie di somministrazione';
COMMENT ON TABLE ESITO_SOMM_DEF IS 'Esiti delle somministrazioni';
COMMENT ON TABLE STATO_MANUTENZIONE_DEF IS 'Stati degli interventi di manutenzione';
COMMENT ON TABLE GIORNO_SETTIMANA IS 'Giorni della settimana';
COMMENT ON TABLE TIPOLOGIA_DIETA IS 'Tipologie di dieta';
COMMENT ON TABLE TIPO_CUOCO_DEF IS 'Tipologie di cucina';
COMMENT ON TABLE SETTORE_MANUTENZIONE_DEF IS 'Settori di manutenzione';

COMMENT ON TABLE PERSONA IS 'Anagrafica persone fisiche';
COMMENT ON TABLE ENTE IS 'Enti pubblici o privati';
COMMENT ON TABLE DOCUMENTO IS 'Documenti delle persone';
COMMENT ON TABLE CONTRATTO IS 'Tipologie contrattuali';
COMMENT ON TABLE PERSONALE IS 'Dipendenti della RSA';
COMMENT ON TABLE MEDICO IS 'Medici specialistici';
COMMENT ON TABLE OPERATORE IS 'Operatori socio-sanitari';
COMMENT ON TABLE REPARTO IS 'Reparti della RSA';
COMMENT ON TABLE CAMERA IS 'Camere/degenze';
COMMENT ON TABLE RESIDENTE IS 'Ospiti della RSA';
COMMENT ON TABLE FARMACO IS 'Farmaci in dotazione';
COMMENT ON TABLE SOMMINISTRAZIONE IS 'Log somministrazioni farmaci';
COMMENT ON TABLE MALATTIA IS 'Patologie nosologiche';
COMMENT ON TABLE PAI IS 'Piani assistenziali individuali';
COMMENT ON TABLE DIETA IS 'Diete disponibili';
COMMENT ON TABLE AZIENDA_ESTERNA IS 'Aziende fornitrici servizi';
COMMENT ON TABLE DITTA_PULIZIA IS 'Aziende di pulizie';
COMMENT ON TABLE DITTA_RISTORANTE IS 'Aziende di ristorazione';
COMMENT ON TABLE DITTA_MANUTENZIONE IS 'Aziende di manutenzione';
COMMENT ON TABLE MANUTENZIONE IS 'Interventi di manutenzione';
COMMENT ON TABLE PRENOTAZIONE IS 'Prenotazioni visite/appuntamenti';
COMMENT ON TABLE TURNO IS 'Turni di lavoro del personale';
COMMENT ON TABLE PARENTE IS 'Parenti dei residenti';
COMMENT ON TABLE TUTORE IS 'Tutori legali';
COMMENT ON TABLE GESTISCE IS 'Medici e reparti gestiti';
COMMENT ON TABLE ALLOGGIA IS 'Assegnazioni camera-residente';
COMMENT ON TABLE SOFFRE IS 'Residenti e patologie';
COMMENT ON TABLE SEGUE IS 'Residenti e diete';
COMMENT ON TABLE FORNISCE IS 'Dieta e ditte fornitrici';
COMMENT ON TABLE PULISCE IS 'Pulizie camere per giorno';
COMMENT ON TABLE EFFETTUA IS 'Interventi e ditte manutenzione';
COMMENT ON TABLE RICHIEDE IS 'Documenti richiesti per prenotazioni';
COMMENT ON TABLE COMPILA IS 'PAI e medici compilatori';
COMMENT ON TABLE RAPPRESENTA IS 'Tutori e parenti rappresentati';
COMMENT ON TABLE VISITA IS 'Visite mediche ai residenti';

COMMENT ON COLUMN PERSONA.CF IS 'Codice fiscale 16 caratteri';
COMMENT ON COLUMN PERSONA.CE_CITTA_NASCITA IS 'Comune di nascita';
COMMENT ON COLUMN PERSONA.CE_CITTA_RESIDENZA IS 'Comune di residenza';
COMMENT ON COLUMN PERSONA.NOME IS 'Nome';
COMMENT ON COLUMN PERSONA.COGNOME IS 'Cognome';
COMMENT ON COLUMN PERSONA.DATA_NASCITA IS 'Data di nascita';

COMMENT ON COLUMN ENTE.P_IVA IS 'Partita IVA 11 cifre';
COMMENT ON COLUMN ENTE.NOME_ENTE IS 'Denominazione';
COMMENT ON COLUMN ENTE.CE_CITTA_SEDE IS 'Sede legale';

COMMENT ON COLUMN DOCUMENTO.CE_PERSONA_CF IS 'Persona titolare';
COMMENT ON COLUMN DOCUMENTO.CODICE_DOCUMENTO IS 'Numero documento';
COMMENT ON COLUMN DOCUMENTO.CE_ENTE_PIVA IS 'Ente emittente';
COMMENT ON COLUMN DOCUMENTO.SCADENZA IS 'Data scadenza';

COMMENT ON COLUMN CONTRATTO.ID_CONTRATTO IS 'Identificativo contratto';
COMMENT ON COLUMN CONTRATTO.TASSA_DETRATTA IS 'Percentuale tassa detratta';
COMMENT ON COLUMN CONTRATTO.PAGA_ORARIA IS 'Retribuzione oraria lorda';
COMMENT ON COLUMN CONTRATTO.CE_TIPO_CONTRATTO IS 'Tipologia contrattuale';

COMMENT ON COLUMN PERSONALE.CE_PERSONA_CF IS 'Persona/FK';
COMMENT ON COLUMN PERSONALE.DATA_ASSUNZIONE IS 'Data assunzione';
COMMENT ON COLUMN PERSONALE.CE_TURNO IS 'Turno abituale';
COMMENT ON COLUMN PERSONALE.CE_CONTRATTO IS 'Contratto applicato';

COMMENT ON COLUMN MEDICO.CE_PERSONALE_CF IS 'Personale/FK';
COMMENT ON COLUMN MEDICO.CE_SPECIALIZZAZIONE IS 'Specializzazione';
COMMENT ON COLUMN MEDICO.NUMERO_ALBO IS 'Numero iscrizione albo';

COMMENT ON COLUMN OPERATORE.CE_PERSONALE_CF IS 'Personale/FK';
COMMENT ON COLUMN OPERATORE.CE_QUALIFICA IS 'Qualifica (OSS/infermiere)';

COMMENT ON COLUMN REPARTO.ID_REPARTO IS 'Identificativo reparto';
COMMENT ON COLUMN REPARTO.DENOMINAZIONE IS 'Nome reparto';
COMMENT ON COLUMN REPARTO.CE_MEDICO_RESP IS 'Medico responsabile';

COMMENT ON COLUMN CAMERA.ID_CAMERA IS 'Identificativo camera';
COMMENT ON COLUMN CAMERA.NUMERO_STANZA IS 'Numero stanza';
COMMENT ON COLUMN CAMERA.PIANO IS 'Piano edificio';
COMMENT ON COLUMN CAMERA.LETTI_TOTALI IS 'Posti letto (1-4)';
COMMENT ON COLUMN CAMERA.CE_ID_REPARTO IS 'Reparto appartenenza';

COMMENT ON COLUMN RESIDENTE.CE_PERSONA_CF IS 'Persona/FK';
COMMENT ON COLUMN RESIDENTE.CE_CAMERA IS 'Camera assegnata';
COMMENT ON COLUMN RESIDENTE.CE_MEDICO_CURANTE IS 'Medico curante';
COMMENT ON COLUMN RESIDENTE.DATA_INGRESSO IS 'Data ingresso';
COMMENT ON COLUMN RESIDENTE.CE_STATO_SALUTE IS 'Stato di salute';

COMMENT ON COLUMN FARMACO.CODICE_AIC IS 'Codice AIC';
COMMENT ON COLUMN FARMACO.NOME_FARMACO IS 'Nome commerciale';
COMMENT ON COLUMN FARMACO.DOSE IS 'Dosaggio';
COMMENT ON COLUMN FARMACO.CE_FASCIA_ORARIA IS 'Fascia oraria';

COMMENT ON COLUMN SOMMINISTRAZIONE.ID_LOG_SANITARIO IS 'ID progressivo';
COMMENT ON COLUMN SOMMINISTRAZIONE.CE_RESIDENTE_CF IS 'Residente';
COMMENT ON COLUMN SOMMINISTRAZIONE.CE_FARMACO_AIC IS 'Farmaco';
COMMENT ON COLUMN SOMMINISTRAZIONE.CE_OPERATORE_CF IS 'Operatore';
COMMENT ON COLUMN SOMMINISTRAZIONE.DATA_ORA_SOMM IS 'Data/ora';
COMMENT ON COLUMN SOMMINISTRAZIONE.CE_ESITO IS 'Esito';

COMMENT ON COLUMN MALATTIA.CODICE_MALATTIA IS 'Codice patologia';
COMMENT ON COLUMN MALATTIA.NOME_MALATTIA IS 'Nome malattia';
COMMENT ON COLUMN MALATTIA.DESCRIZIONE_MALATTIA IS 'Descrizione clinica';
COMMENT ON COLUMN MALATTIA.LIVELLO_GRAVITA IS 'Gravita 1-5';

COMMENT ON COLUMN DIETA.NOME_DIETA IS 'Nome dieta';
COMMENT ON COLUMN DIETA.CE_TIPOLOGIA IS 'Tipologia';
COMMENT ON COLUMN DIETA.PATOLOGIA_EXTRA IS 'Patologia associata';

COMMENT ON COLUMN PAI.CODICE_PAI IS 'Codice PAI';
COMMENT ON COLUMN PAI.CE_RESIDENTE_CF IS 'Residente';
COMMENT ON COLUMN PAI.DATA_REDAZIONE IS 'Data redazione';
COMMENT ON COLUMN PAI.DATA_REVISIONE IS 'Ultima revisione';
COMMENT ON COLUMN PAI.DIAGNOSI IS 'Diagnosi';
COMMENT ON COLUMN PAI.OBIETTIVI IS 'Obiettivi assistenziali';
COMMENT ON COLUMN PAI.TRATTAMENTO IS 'Trattamento';
COMMENT ON COLUMN PAI.RAGGIUNTO IS 'Obiettivi raggiunti S/N';
COMMENT ON COLUMN PAI.DATA_DIMISSIONE_PAI IS 'Data dimissione';

COMMENT ON COLUMN MANUTENZIONE.ID_INTERVENTO IS 'Identificativo intervento';
COMMENT ON COLUMN MANUTENZIONE.CE_DITTA_PIVA IS 'Ditta incaricata';
COMMENT ON COLUMN MANUTENZIONE.CE_STATO IS 'Stato intervento';
COMMENT ON COLUMN MANUTENZIONE.DATA_INIZIO_INTERVENTO IS 'Data inizio';
COMMENT ON COLUMN MANUTENZIONE.DESCRIZIONE_GUASTO IS 'Descrizione guasto';
COMMENT ON COLUMN MANUTENZIONE.COSTO IS 'Costo';

COMMENT ON COLUMN PRENOTAZIONE.CODICE_PRENOTAZIONE IS 'Codice prenotazione';
COMMENT ON COLUMN PRENOTAZIONE.CE_CAMERA IS 'Camera';
COMMENT ON COLUMN PRENOTAZIONE.CE_RESIDENTE_CF IS 'Residente';
COMMENT ON COLUMN PRENOTAZIONE.DATA_PRENOTAZIONE IS 'Data creazione';
COMMENT ON COLUMN PRENOTAZIONE.CF_PRENOTATORE IS 'Prenotatore';
COMMENT ON COLUMN PRENOTAZIONE.DESCRIZIONE_PRENOTAZIONE IS 'Note';
COMMENT ON COLUMN PRENOTAZIONE.DATA_DIMISSIONE_PREVISTA IS 'Dimissione prevista';
COMMENT ON COLUMN PRENOTAZIONE.GIORNO_PRENOTAZIONE IS 'Giorno';
COMMENT ON COLUMN PRENOTAZIONE.ORA_INIZIO_PRENOTAZIONE IS 'Ora inizio';
COMMENT ON COLUMN PRENOTAZIONE.ORA_FINE_PRENOTAZIONE IS 'Ora fine';

COMMENT ON COLUMN TURNO.ID_TURNO IS 'Identificativo turno';
COMMENT ON COLUMN TURNO.CE_PERSONALE_CF IS 'Personale';
COMMENT ON COLUMN TURNO.GIORNO_TURNO IS 'Giorno';
COMMENT ON COLUMN TURNO.ORA_INIZIO_TURNO IS 'Ora inizio';
COMMENT ON COLUMN TURNO.ORA_FINE_TURNO IS 'Ora fine';

COMMENT ON COLUMN VISITA.GIORNO_VISITA IS 'Giorno visita';
COMMENT ON COLUMN VISITA.ORA_INGRESSO IS 'Ora inizio';
COMMENT ON COLUMN VISITA.ORA_USCITA IS 'Ora fine';
