ALTER SESSION SET CONTAINER=RSA;

CREATE TABLE REGIONE_ITALIANA (
    ID_REGIONE  CHAR(2)     PRIMARY KEY,
    NOME        VARCHAR2(64) NOT NULL UNIQUE
);

CREATE TABLE PROVINCIA_ITALIANA (
    SIGLA       CHAR(2)     PRIMARY KEY,
    NOME        VARCHAR2(64) NOT NULL UNIQUE,
    CE_REGIONE  CHAR(2)     NOT NULL REFERENCES REGIONE_ITALIANA(ID_REGIONE)
);

CREATE TABLE CITTA_ITALIANA (
    ID_COMUNE   CHAR(6)     PRIMARY KEY,
    NOME        VARCHAR2(64) NOT NULL,
    CE_PROVINCIA CHAR(2)    NOT NULL REFERENCES PROVINCIA_ITALIANA(SIGLA)
);

CREATE TABLE TIPO_CONTRATTO_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE TURNO_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE SPECIALIZZAZIONE (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(64) NOT NULL UNIQUE
);

CREATE TABLE QUALIFICA_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE STATO_SALUTE_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE FASCIA_ORARIA_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE ESITO_SOMM_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE STATO_MANUTENZIONE_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE GIORNO_SETTIMANA (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(16) NOT NULL UNIQUE
);

CREATE TABLE TIPOLOGIA_DIETA (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE TIPO_CUOCO_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE SETTORE_MANUTENZIONE_DEF (
    ID          VARCHAR2(16) PRIMARY KEY,
    DESCRIZIONE VARCHAR2(32) NOT NULL UNIQUE
);

CREATE TABLE PERSONA (
    CF                CHAR(16)            PRIMARY KEY,
    NOME              VARCHAR2(64)        NOT NULL,
    COGNOME           VARCHAR2(64)        NOT NULL,
    DATA_NASCITA      DATE                NOT NULL,
    CE_CITTA_NASCITA  CHAR(6)             NOT NULL REFERENCES CITTA_ITALIANA(ID_COMUNE),
    CE_CITTA_RESIDENZA CHAR(6)            NOT NULL REFERENCES CITTA_ITALIANA(ID_COMUNE),
    CONSTRAINT PERSONA_CF_FORMATO CHECK (REGEXP_LIKE(CF, '^[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z]$'))
);

CREATE TABLE ENTE (
    P_IVA             CHAR(11)            PRIMARY KEY,
    NOME_ENTE         VARCHAR2(128)       NOT NULL,
    CE_CITTA_SEDE     CHAR(6)             NOT NULL REFERENCES CITTA_ITALIANA(ID_COMUNE),
    CONSTRAINT ENTE_PIVA_FORMATO CHECK (REGEXP_LIKE(P_IVA, '^[0-9]{11}$'))
);

CREATE TABLE DOCUMENTO (
    CE_PERSONA_CF     CHAR(16)            NOT NULL,
    CODICE_DOCUMENTO  VARCHAR2(32)        NOT NULL,
    CE_ENTE_PIVA      CHAR(11),
    SCADENZA          DATE,
    CONSTRAINT DOCUMENTO PRIMARY KEY (CE_PERSONA_CF, CODICE_DOCUMENTO),
    CONSTRAINT DOC_PERSONA FOREIGN KEY (CE_PERSONA_CF) REFERENCES PERSONA(CF) ON DELETE CASCADE,
    CONSTRAINT DOC_ENTE FOREIGN KEY (CE_ENTE_PIVA) REFERENCES ENTE(P_IVA)
);

CREATE TABLE CONTRATTO (
    ID_CONTRATTO      VARCHAR2(32)        PRIMARY KEY,
    TASSA_DETRATTA    NUMBER(8,2)         NOT NULL,
    PAGA_ORARIA       NUMBER(8,2)         NOT NULL,
    CE_TIPO_CONTRATTO VARCHAR2(16)        NOT NULL REFERENCES TIPO_CONTRATTO_DEF(ID)
);

CREATE TABLE PERSONALE (
    CE_PERSONA_CF     CHAR(16)            PRIMARY KEY,
    DATA_ASSUNZIONE   DATE                NOT NULL,
    CE_TURNO          VARCHAR2(16)        NOT NULL REFERENCES TURNO_DEF(ID),
    CE_CONTRATTO      VARCHAR2(32)        NOT NULL REFERENCES CONTRATTO(ID_CONTRATTO),
    CONSTRAINT PERS_PERSONA FOREIGN KEY (CE_PERSONA_CF) REFERENCES PERSONA(CF) ON DELETE CASCADE
);

CREATE TABLE MEDICO (
    CE_PERSONALE_CF   CHAR(16)            PRIMARY KEY,
    CE_SPECIALIZZAZIONE VARCHAR2(16)      NOT NULL REFERENCES SPECIALIZZAZIONE(ID),
    NUMERO_ALBO       VARCHAR2(16)        NOT NULL UNIQUE,
    CONSTRAINT MED_PERS FOREIGN KEY (CE_PERSONALE_CF) REFERENCES PERSONALE(CE_PERSONA_CF) ON DELETE CASCADE
);

CREATE TABLE OPERATORE (
    CE_PERSONALE_CF   CHAR(16)            PRIMARY KEY,
    CE_QUALIFICA      VARCHAR2(16)        NOT NULL REFERENCES QUALIFICA_DEF(ID),
    CONSTRAINT OP_PERS FOREIGN KEY (CE_PERSONALE_CF) REFERENCES PERSONALE(CE_PERSONA_CF) ON DELETE CASCADE
);

CREATE TABLE REPARTO (
    ID_REPARTO        VARCHAR2(16)        PRIMARY KEY,
    DENOMINAZIONE     VARCHAR2(64)        NOT NULL UNIQUE,
    CE_MEDICO_RESP    CHAR(16),
    CONSTRAINT REP_MEDICO FOREIGN KEY (CE_MEDICO_RESP) REFERENCES MEDICO(CE_PERSONALE_CF)
);

CREATE TABLE CAMERA (
    ID_CAMERA         VARCHAR2(16)        PRIMARY KEY,
    NUMERO_STANZA     NUMBER(8,0)         NOT NULL,
    PIANO             NUMBER(8,0)         NOT NULL,
    LETTI_TOTALI      NUMBER(8,0)         NOT NULL,
    CE_ID_REPARTO     VARCHAR2(16)        NOT NULL,
    CONSTRAINT CAMERA_POSTI CHECK (LETTI_TOTALI BETWEEN 1 AND 4),
    CONSTRAINT CAM_REPARTO FOREIGN KEY (CE_ID_REPARTO) REFERENCES REPARTO(ID_REPARTO) ON DELETE CASCADE
);

CREATE TABLE RESIDENTE (
    CE_PERSONA_CF     CHAR(16)            PRIMARY KEY,
    CE_CAMERA         VARCHAR2(16)        NOT NULL REFERENCES CAMERA(ID_CAMERA),
    CE_MEDICO_CURANTE CHAR(16)            REFERENCES MEDICO(CE_PERSONALE_CF),
    DATA_INGRESSO     DATE                DEFAULT TRUNC(SYSDATE) NOT NULL,
    CE_STATO_SALUTE   VARCHAR2(16)        NOT NULL REFERENCES STATO_SALUTE_DEF(ID),
    CONSTRAINT RES_PERSONA FOREIGN KEY (CE_PERSONA_CF) REFERENCES PERSONA(CF) ON DELETE CASCADE
);

CREATE TABLE FARMACO (
    CODICE_AIC        VARCHAR2(16)        PRIMARY KEY,
    NOME_FARMACO      VARCHAR2(128)       NOT NULL,
    DOSE              VARCHAR2(32)        NOT NULL,
    CE_FASCIA_ORARIA  VARCHAR2(16)        NOT NULL REFERENCES FASCIA_ORARIA_DEF(ID)
);

CREATE TABLE SOMMINISTRAZIONE (
    ID_LOG_SANITARIO  NUMBER              GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    CE_FARMACO_AIC    VARCHAR2(16)        NOT NULL REFERENCES FARMACO(CODICE_AIC),
    CE_OPERATORE_CF   CHAR(16)            NOT NULL REFERENCES OPERATORE(CE_PERSONALE_CF),
    DATA_ORA_SOMM     TIMESTAMP(0)        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CE_ESITO          VARCHAR2(16)        NOT NULL REFERENCES ESITO_SOMM_DEF(ID)
);

CREATE TABLE MALATTIA (
    CODICE_MALATTIA   VARCHAR2(16)        PRIMARY KEY,
    NOME_MALATTIA     VARCHAR2(128)       NOT NULL,
    DESCRIZIONE_MALATTIA VARCHAR2(256),
    LIVELLO_GRAVITA   NUMBER(8,0)         CHECK (LIVELLO_GRAVITA BETWEEN 1 AND 5)
);

CREATE TABLE PAI (
    CODICE_PAI        VARCHAR2(16)        PRIMARY KEY,
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    DATA_REDAZIONE    DATE                NOT NULL,
    DATA_REVISIONE    DATE,
    DIAGNOSI          VARCHAR2(512),
    OBIETTIVI         VARCHAR2(512),
    TRATTAMENTO       VARCHAR2(512),
    RAGGIUNTO         CHAR(1)             DEFAULT 'N' CHECK (RAGGIUNTO IN ('S', 'N')),
    DATA_DIMISSIONE_PAI   DATE
);

CREATE TABLE DIETA (
    NOME_DIETA        VARCHAR2(64)        PRIMARY KEY,
    CE_TIPOLOGIA      VARCHAR2(16)        NOT NULL REFERENCES TIPOLOGIA_DIETA(ID),
    PATOLOGIA_EXTRA   VARCHAR2(256)
);

CREATE TABLE AZIENDA_ESTERNA (
    P_IVA             CHAR(11)            PRIMARY KEY,
    NOME_AZIENDA      VARCHAR2(128)       NOT NULL,
    SEDE_LEGALE       VARCHAR2(128),
    SEDE_OPERATIVA    VARCHAR2(128),
    CONSTRAINT AZIENDA_PIVA CHECK (REGEXP_LIKE(P_IVA, '^[0-9]{11}$'))
);

CREATE TABLE DITTA_PULIZIA (
    CE_PIVA           CHAR(11)            PRIMARY KEY REFERENCES AZIENDA_ESTERNA(P_IVA) ON DELETE CASCADE
);

CREATE TABLE DITTA_RISTORANTE (
    CE_PIVA           CHAR(11)            PRIMARY KEY REFERENCES AZIENDA_ESTERNA(P_IVA) ON DELETE CASCADE,
    CE_TIPO_CUOCO     VARCHAR2(16)        REFERENCES TIPO_CUOCO_DEF(ID)
);

CREATE TABLE DITTA_MANUTENZIONE (
    CE_PIVA           CHAR(11)            PRIMARY KEY REFERENCES AZIENDA_ESTERNA(P_IVA) ON DELETE CASCADE,
    CE_SETTORE        VARCHAR2(16)        REFERENCES SETTORE_MANUTENZIONE_DEF(ID)
);

CREATE TABLE MANUTENZIONE (
    ID_INTERVENTO     VARCHAR2(16)        PRIMARY KEY,
    CE_DITTA_PIVA     CHAR(11)            NOT NULL REFERENCES DITTA_MANUTENZIONE(CE_PIVA) ON DELETE CASCADE,
    CE_STATO          VARCHAR2(16)        NOT NULL REFERENCES STATO_MANUTENZIONE_DEF(ID),
    DATA_INIZIO_INTERVENTO DATE            NOT NULL,
    DESCRIZIONE_GUASTO VARCHAR2(512),
    COSTO             NUMBER(8,2)
);

CREATE TABLE PRENOTAZIONE (
    CODICE_PRENOTAZIONE VARCHAR2(32)       PRIMARY KEY,
    CE_CAMERA         VARCHAR2(16)        REFERENCES CAMERA(ID_CAMERA),
    CE_RESIDENTE_CF   CHAR(16)            REFERENCES RESIDENTE(CE_PERSONA_CF),
    DATA_PRENOTAZIONE DATE                NOT NULL,
    CF_PRENOTATORE    CHAR(16)            NOT NULL REFERENCES PERSONA(CF),
    DESCRIZIONE_PRENOTAZIONE VARCHAR2(256),
    DATA_DIMISSIONE_PREVISTA DATE,
    GIORNO_PRENOTAZIONE   DATE,
    ORA_INIZIO_PRENOTAZIONE TIMESTAMP(0),
    ORA_FINE_PRENOTAZIONE   TIMESTAMP(0)
);

CREATE TABLE TURNO (
    ID_TURNO          VARCHAR2(16)        PRIMARY KEY,
    CE_PERSONALE_CF   CHAR(16)            NOT NULL REFERENCES PERSONALE(CE_PERSONA_CF) ON DELETE CASCADE,
    GIORNO_TURNO      DATE                NOT NULL,
    ORA_INIZIO_TURNO  TIMESTAMP(0)        NOT NULL,
    ORA_FINE_TURNO    TIMESTAMP(0)        NOT NULL
);

CREATE TABLE PARENTE (
    CE_PERSONA_CF     CHAR(16)            PRIMARY KEY REFERENCES PERSONA(CF) ON DELETE CASCADE
);

CREATE TABLE TUTORE (
    CE_PARENTE_CF     CHAR(16)            PRIMARY KEY REFERENCES PARENTE(CE_PERSONA_CF) ON DELETE CASCADE
);

CREATE TABLE GESTISCE (
    CE_REPARTO        VARCHAR2(16)        NOT NULL REFERENCES REPARTO(ID_REPARTO) ON DELETE CASCADE,
    CE_MEDICO_CF      CHAR(16)            NOT NULL REFERENCES MEDICO(CE_PERSONALE_CF) ON DELETE CASCADE,
    DATA_INIZIO_GESTIONE DATE             DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT GESTISCE PRIMARY KEY (CE_REPARTO, CE_MEDICO_CF)
);

CREATE TABLE ALLOGGIA (
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    CE_CAMERA         VARCHAR2(16)        NOT NULL REFERENCES CAMERA(ID_CAMERA) ON DELETE CASCADE,
    DATA_ASSEGNAZIONE DATE                DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT ALLOGGIA PRIMARY KEY (CE_RESIDENTE_CF, CE_CAMERA, DATA_ASSEGNAZIONE)
);

CREATE TABLE SOFFRE (
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    CE_MALATTIA       VARCHAR2(16)        NOT NULL REFERENCES MALATTIA(CODICE_MALATTIA) ON DELETE CASCADE,
    CONSTRAINT SOFFRE PRIMARY KEY (CE_RESIDENTE_CF, CE_MALATTIA)
);

CREATE TABLE SEGUE (
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    CE_DIETA          VARCHAR2(64)        NOT NULL REFERENCES DIETA(NOME_DIETA) ON DELETE CASCADE,
    DATA_INIZIO_DIETA DATE                DEFAULT TRUNC(SYSDATE) NOT NULL,
    CONSTRAINT SEGUE PRIMARY KEY (CE_RESIDENTE_CF, CE_DIETA, DATA_INIZIO_DIETA)
);

CREATE TABLE FORNISCE (
    CE_DIETA          VARCHAR2(64)        NOT NULL REFERENCES DIETA(NOME_DIETA) ON DELETE CASCADE,
    CE_DITTA_PIVA     CHAR(11)            NOT NULL REFERENCES DITTA_RISTORANTE(CE_PIVA) ON DELETE CASCADE,
    CONSTRAINT FORNISCE PRIMARY KEY (CE_DIETA, CE_DITTA_PIVA)
);

CREATE TABLE PULISCE (
    CE_CAMERA         VARCHAR2(16)        NOT NULL REFERENCES CAMERA(ID_CAMERA) ON DELETE CASCADE,
    CE_DITTA_PIVA     CHAR(11)            NOT NULL REFERENCES DITTA_PULIZIA(CE_PIVA) ON DELETE CASCADE,
    CE_GIORNO         VARCHAR2(16)        NOT NULL REFERENCES GIORNO_SETTIMANA(ID),
    CONSTRAINT PULISCE PRIMARY KEY (CE_CAMERA, CE_DITTA_PIVA, CE_GIORNO)
);

CREATE TABLE EFFETTUA (
    CE_INTERVENTO     VARCHAR2(16)        NOT NULL REFERENCES MANUTENZIONE(ID_INTERVENTO) ON DELETE CASCADE,
    CE_DITTA_PIVA     CHAR(11)            NOT NULL REFERENCES DITTA_MANUTENZIONE(CE_PIVA) ON DELETE CASCADE,
    CONSTRAINT EFFETTUA PRIMARY KEY (CE_INTERVENTO, CE_DITTA_PIVA)
);

CREATE TABLE RICHIEDE (
    CE_PRENOTAZIONE   VARCHAR2(32)        NOT NULL REFERENCES PRENOTAZIONE(CODICE_PRENOTAZIONE) ON DELETE CASCADE,
    CE_PERSONA_CF     CHAR(16)            NOT NULL,
    CE_CODICE_DOC     VARCHAR2(32)        NOT NULL,
    CONSTRAINT RICHIEDE PRIMARY KEY (CE_PRENOTAZIONE, CE_PERSONA_CF, CE_CODICE_DOC),
    CONSTRAINT RIC_DOC FOREIGN KEY (CE_PERSONA_CF, CE_CODICE_DOC) REFERENCES DOCUMENTO(CE_PERSONA_CF, CODICE_DOCUMENTO) ON DELETE CASCADE
);

CREATE TABLE COMPILA (
    CE_PAI            VARCHAR2(16)        NOT NULL REFERENCES PAI(CODICE_PAI) ON DELETE CASCADE,
    CE_MEDICO_CF      CHAR(16)            NOT NULL REFERENCES MEDICO(CE_PERSONALE_CF) ON DELETE CASCADE,
    CONSTRAINT COMPILA PRIMARY KEY (CE_PAI, CE_MEDICO_CF)
);

CREATE TABLE RAPPRESENTA (
    CE_TUTORE_CF      CHAR(16)            NOT NULL REFERENCES TUTORE(CE_PARENTE_CF) ON DELETE CASCADE,
    CE_PARENTE_CF     CHAR(16)            NOT NULL REFERENCES PARENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    CONSTRAINT RAPPRESENTA PRIMARY KEY (CE_TUTORE_CF, CE_PARENTE_CF)
);

CREATE TABLE VISITA (
    CE_MEDICO_CF      CHAR(16)            NOT NULL REFERENCES MEDICO(CE_PERSONALE_CF) ON DELETE CASCADE,
    CE_RESIDENTE_CF   CHAR(16)            NOT NULL REFERENCES RESIDENTE(CE_PERSONA_CF) ON DELETE CASCADE,
    GIORNO_VISITA     DATE                NOT NULL,
    ORA_INGRESSO      TIMESTAMP(0)        NOT NULL,
    ORA_USCITA        TIMESTAMP(0),
    CONSTRAINT VISITA PRIMARY KEY (CE_MEDICO_CF, CE_RESIDENTE_CF, GIORNO_VISITA)
);
