ALTER SESSION SET CONTAINER=RSA;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER VALIDAZIONE_CAPIENZA_CAMERA';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4080 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER VALIDAZIONE_CAPIENZA_CAMERA
    BEFORE INSERT OR UPDATE ON RESIDENTE
    FOR EACH ROW
DECLARE
    NUMERO_POSTI_MASSIMI NUMBER;
    NUMERO_OCCUPANTI_ATTUALI NUMBER;
BEGIN
    SELECT LETTI_TOTALI INTO NUMERO_POSTI_MASSIMI 
    FROM CAMERA 
    WHERE ID_CAMERA = :NEW.CE_CAMERA 
    FOR UPDATE;
    
    SELECT COUNT(*) INTO NUMERO_OCCUPANTI_ATTUALI 
    FROM RESIDENTE 
    WHERE CE_CAMERA = :NEW.CE_CAMERA;
    
    IF NUMERO_OCCUPANTI_ATTUALI >= NUMERO_POSTI_MASSIMI THEN
        RAISE_APPLICATION_ERROR(-20001, 'SUPERAMENTO LIMITE POSTI LETTO PER LA CAMERA SPECIFICATA');
    END IF;
END VALIDAZIONE_CAPIENZA_CAMERA;
/
